"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-albuf4*6@+7)3viufn1zxi*%ba5i37_w=m6nn%qh@x+ta^+4)j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = [ ]

#variables para envio de correo
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'dennysreyes98@gmail.com'
EMAIL_HOST_PASSWORD = 'fubklbkilekawqtn'
EMAIL_PORT = 587

#python anywhere
ALLOWED_HOSTS = [
    'https://medicalbrokers.pythonanywhere.com',
    'dennyssoft2023.pythonanywhere.com',
    'medicalbrokers.pythonanywhere.com',
    'localhost',
    'localhost:8000',
    'localhost:8100',
    'localhost:4200'
    ]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    # Los modulos que uds necesiten#
    'crm', # Archivo necesario para CRM
    'movil',
    'web',
    'auth_manage',
    # allow local cors
    'corsheaders',
    'front'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #allow local cors
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]
'''
#cors local

'''
'''
CORS_ORIGIN_WHITELIST=[
    'http://localhost',
    'http://localhost:4200',

]
'''

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOWED_ORIGINS = [
    "https://example.com",
    "https://sub.example.com",
    "http://localhost:4200",
    "http://127.0.0.1:4200",
]


#pythonanywhere, permitir brokerWeb frontend

CORS_ORIGIN_WHITELIST=(
    'http://localhost',
    'http://localhost:4200',
    'http://localhost:3000',
    'https://brokersegurosfrontend.herokuapp.com',
    'https://mbfront2022.herokuapp.com',
    'http://medicalbrokers.pythonanywhere.com',
    'http://dennyssoft2023.pythonanywhere.com'
)


ROOT_URLCONF = 'Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'NAME': 'brokers',
#         'ENGINE': 'django.db.backends.mysql',
#         'USER': 'root',
#         'PASSWORD': 'admin'
#     }
# }

# DATABASES = {
#     'default': {
#         'NAME': 'dennyssoft2023$medicalbrokers',
#         'ENGINE': 'django.db.backends.mysql',
#         'USER': 'dennyssoft2023',
#         'PASSWORD': 'Python2023',
#         'HOST': 'dennyssoft2023.mysql.pythonanywhere-services.com'
#     }
#}
DATABASES ={

     'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'heroku_9c355e644caa4b7',
        'USER': 'b008c35df7fd93',
        'PASSWORD': '98c360b6',
        'HOST': 'us-cdbr-east-06.cleardb.net',
    }
}



#PythonAnywhere Configuración de base de datos
""" 
DATABASES ={

     'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'MedicalBrokers$brokers',
        'USER': 'MedicalBrokers',
        'PASSWORD': 'contra123',
        'HOST': 'MedicalBrokers.mysql.pythonanywhere-services.com',
    }
}
 """
# SuperUser
# broker ->user
# broker2022 ->pass

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
# pythonanywhere statics
#STATIC_ROOT = '/home/MedicalBrokers/brokers-api/backend/static'
STATIC_ROOT = 'static/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}
