# Generated by Django 4.1 on 2022-08-26 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='compania',
            table='Compania',
        ),
    ]
