# Generated by Django 4.1 on 2022-08-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_compania_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compania',
            options={},
        ),
    ]
