# Generated by Django 4.1 on 2022-08-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_compania_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deducible',
            fields=[
                ('idDeducible', models.AutoField(db_column='idDeducible', primary_key=True, serialize=False)),
                ('tipoDeducible', models.CharField(blank=True, db_column='tipoDeducible', max_length=45, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('fecha_creado', models.DateField(blank=True, null=True)),
                ('creado_por_usuario', models.CharField(blank=True, max_length=45, null=True)),
                ('creado_id_usuario', models.IntegerField(blank=True, null=True)),
                ('fecha_modificado', models.DateField(blank=True, null=True)),
                ('modificado_por_usuario', models.CharField(blank=True, max_length=45, null=True)),
                ('modificado_id_usuario', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Deducible',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('idPlan', models.AutoField(db_column='idPlan', primary_key=True, serialize=False)),
                ('tipoDePlan', models.CharField(blank=True, db_column='tipoDePlan', max_length=45, null=True)),
                ('tipoDeSeguro', models.CharField(blank=True, db_column='tipoDeSeguro', max_length=45, null=True)),
                ('nombrePlan', models.CharField(blank=True, db_column='nombrePlan', max_length=45, null=True)),
                ('tieneLimite', models.IntegerField(blank=True, db_column='tieneLimite', null=True)),
                ('cobertura', models.FloatField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('fecha_creado', models.DateField(blank=True, null=True)),
                ('creado_por_usuario', models.CharField(blank=True, max_length=45, null=True)),
                ('creado_id_usuario', models.IntegerField(blank=True, null=True)),
                ('fecha_modificado', models.DateField(blank=True, null=True)),
                ('modificado_por_usuario', models.CharField(blank=True, max_length=45, null=True)),
                ('modificado_id_usuario', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Plan',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='compania',
            options={'managed': False},
        ),
    ]
