# Generated by Django 3.2 on 2022-12-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_formulario_contactenos'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario_contactenos',
            name='edad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formulario_contactenos',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
