# Generated by Django 3.2 on 2022-12-16 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20221205_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hasta', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_antes', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_despues', models.CharField(blank=True, max_length=100, null=True)),
                ('cobertura_accidentes', models.CharField(blank=True, max_length=100, null=True)),
                ('idplan', models.ForeignKey(db_column='idPlan', on_delete=django.db.models.deletion.DO_NOTHING, to='crm.plan')),
            ],
        ),
    ]
