# Generated by Django 3.2 on 2023-01-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_ofertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mis_planes',
            fields=[
                ('idMisPlanes', models.AutoField(db_column='idMisPlanes', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Mis_planes',
                'managed': False,
            },
        ),
    ]
