# Generated by Django 3.2 on 2023-01-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_mis_planes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mis_planes',
        ),
    ]
