# Generated by Django 3.2 on 2023-01-07 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_delete_mis_planes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mis_planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.ForeignKey(blank=True, db_column='idCliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.cliente')),
                ('idplan', models.ForeignKey(blank=True, db_column='idPlan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.plan')),
            ],
        ),
    ]
