# Generated by Django 3.2 on 2023-01-07 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_mis_planes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mis_planes',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='mis_planes',
            name='idPersona',
            field=models.ForeignKey(blank=True, db_column='idPersona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.persona'),
        ),
    ]
